nginx_linuxwt:
   restart: always
   image: nginx
   container_name: nginx_linuxwt
   volumes:
       - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf
       - $PWD/conf/nginx_reverse.conf:/etc/nginx/conf.d/default.conf
       - /etc/localtime:/etc/timezone
       - /www/html:/www/html
   links:
       - tomcat_linuxwt
   privileged: true
   ports:
       - 150:80
       - 80:90
tomcat_linuxwt:
   restart: always
   image: tomcat:maven
   container_name: tomcat_linuxwt
   volumes:
       - $PWD/conf/server.xml:/usr/local/tomcat/conf/server.xml
       - /webapps:/usr/local/tomcat/webapps/root
       - /etc/localtime:/etc/localtime
       - /etc/timezone:/etc/timezone
   expose:
       - 8080
