mysql_linuxwt:
  restart: always
  image: mysql:5.7
  container_name: mysql_linuxwt
  volumes:
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    - $PWD/mysql:/var/lib/mysql
    - $PWD/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
  ports:
    - 33066:3306
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
